export const LandmarkMockData = [
  { objectId: 11, title: 'Dr Nice', shortInfo: 'SUPERPOWER SHORT DESCRIPTION', description: 'THE BIG DESCRIPTION IS HERE | THE BIG DESCRIPTION IS HERE | THE BIG DESCRIPTION IS HERE | THE BIG DESCRIPTION IS HERE | THE BIG DESCRIPTION IS HERE', location:[11.1111, 22.2222], url:"www.somewebsite.eu", photo:"", photo_thumb: '' },
  { objectId: 12, title: 'Narco', shortInfo: 'SUPERPOWER SHORT DESCRIPTION', description: 'THE BIG DESCRIPTION IS HERE | THE BIG DESCRIPTION IS HERE | THE BIG DESCRIPTION IS HERE | THE BIG DESCRIPTION IS HERE | THE BIG DESCRIPTION IS HERE', location:[11.1111, 22.2222], url:"www.somewebsite.eu", photo:"", photo_thumb: '' },
  { objectId: 13, title: 'Bombasto', shortInfo: 'SUPERPOWER SHORT DESCRIPTION', description: 'THE BIG DESCRIPTION IS HERE | THE BIG DESCRIPTION IS HERE | THE BIG DESCRIPTION IS HERE | THE BIG DESCRIPTION IS HERE | THE BIG DESCRIPTION IS HERE', location:[11.1111, 22.2222], url:"www.somewebsite.eu", photo:"", photo_thumb: '' },
  { objectId: 14, title: 'Celeritas', shortInfo: 'SUPERPOWER SHORT DESCRIPTION', description: 'THE BIG DESCRIPTION IS HERE | THE BIG DESCRIPTION IS HERE | THE BIG DESCRIPTION IS HERE | THE BIG DESCRIPTION IS HERE | THE BIG DESCRIPTION IS HERE', location:[11.1111, 22.2222], url:"www.somewebsite.eu", photo:"", photo_thumb: '' },
  { objectId: 15, title: 'Magneta', shortInfo: 'SUPERPOWER SHORT DESCRIPTION', description: 'THE BIG DESCRIPTION IS HERE | THE BIG DESCRIPTION IS HERE | THE BIG DESCRIPTION IS HERE | THE BIG DESCRIPTION IS HERE | THE BIG DESCRIPTION IS HERE', location:[11.1111, 22.2222], url:"www.somewebsite.eu", photo:"", photo_thumb: '' },
  { objectId: 16, title: 'RubberMan', shortInfo: 'SUPERPOWER SHORT DESCRIPTION', description: 'THE BIG DESCRIPTION IS HERE | THE BIG DESCRIPTION IS HERE | THE BIG DESCRIPTION IS HERE | THE BIG DESCRIPTION IS HERE | THE BIG DESCRIPTION IS HERE', location:[11.1111, 22.2222], url:"www.somewebsite.eu", photo:"", photo_thumb: '' },
  { objectId: 17, title: 'Dynama', shortInfo: 'SUPERPOWER SHORT DESCRIPTION', description: 'THE BIG DESCRIPTION IS HERE | THE BIG DESCRIPTION IS HERE | THE BIG DESCRIPTION IS HERE | THE BIG DESCRIPTION IS HERE | THE BIG DESCRIPTION IS HERE', location:[11.1111, 22.2222], url:"www.somewebsite.eu", photo:"", photo_thumb: '' },
  { objectId: 18, title: 'Dr IQ', shortInfo: 'SUPERPOWER SHORT DESCRIPTION', description: 'THE BIG DESCRIPTION IS HERE | THE BIG DESCRIPTION IS HERE | THE BIG DESCRIPTION IS HERE | THE BIG DESCRIPTION IS HERE | THE BIG DESCRIPTION IS HERE', location:[11.1111, 22.2222], url:"www.somewebsite.eu", photo:"", photo_thumb: '' },
  { objectId: 19, title: 'Magma', shortInfo: 'SUPERPOWER SHORT DESCRIPTION', description: 'THE BIG DESCRIPTION IS HERE | THE BIG DESCRIPTION IS HERE | THE BIG DESCRIPTION IS HERE | THE BIG DESCRIPTION IS HERE | THE BIG DESCRIPTION IS HERE', location:[11.1111, 22.2222], url:"www.somewebsite.eu", photo:"", photo_thumb: '' },
  { objectId: 20, title: 'Tornado', shortInfo: 'SUPERPOWER SHORT DESCRIPTION', description: 'THE BIG DESCRIPTION IS HERE | THE BIG DESCRIPTION IS HERE | THE BIG DESCRIPTION IS HERE | THE BIG DESCRIPTION IS HERE | THE BIG DESCRIPTION IS HERE', location:[11.1111, 22.2222], url:"www.somewebsite.eu", photo:"", photo_thumb: '' }
];
